name: Deploy Nuxt site to Pages
on:
  push:
    branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
      - name: Get blog posts
        uses: actions/checkout@v3
        with:
          repository: ${{ vars.CONTENT_REPO }}
          ref: main
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: ./_write
      - name: Get build time
        shell: bash
        run: |
          TZ=Asia/Taipei echo "BUILD_TIME=$(date +'%Y-%m-%dT%H:%M:%S%:z')" >> $GITHUB_ENV
      - name: Static HTML export with Nuxt
        run: pnpm run generate
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: deployment
          path: ./dist

  # Deployment job
  deploy-to-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.github-deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: github-deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: deployment

  deploy-to-netlify:
    environment:
      name: production
      url: ${{ steps.netlify-deployment.outputs.NETLIFY_LIVE_URL }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: deployment
      - name: Extract artifact
        shell: bash
        run: |
          mkdir dist
          tar xf artifact.tar -C ./dist
      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        id: netlify-deployment
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          NETLIFY_DEPLOY_MESSAGE: "Deployed with ${{ vars.GITHUB_SHA }} by GitHub Actions #${{ vars.GITHUB_RUN_ID }} "
          build_directory: dist
          install_command: "echo 'Skipping installing the dependencies'"
          build_command: "echo 'Skipping building the web files'"

  clean-up:
    runs-on: ubuntu-latest
    needs: 
      - deploy-to-github-pages
      - deploy-to-netlify
    steps:
      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v2
        with:
            name: deployment
